### ISSUE TITLE
Incomplete SAM download resulted in error during BAM indexing

### ISSUE THREAD

**Issue by sarahtanja** [course-fish546-2023/assistance-public#11]
Incomplete SAM download resulted in an 'End Of File' (EOF) marker absent error during BAM indexing

### Index the sorted BAM file
```{r, engine='bash'}
# Index the sorted BAM file (multi-threading is not applicable to this operation)
/home/shared/samtools-1.12/samtools index \
../output/F143_cgigas_sorted.bam
```
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[E::bgzf_read_block] Failed to read BGZF block data at offset 5544532487 expected 13889 bytes; hread returned 5607
[E::bgzf_read] Read block operation failed with error 4 after 0 of 4 bytes
samtools index: failed to create index for "../output/F143_cgigas_sorted.bam"

I'm going to go back and try to re-download the whole SAM file...

**Comment by sr320** [comment]
nope - as we talked about yesterday just modify location of sorted bam to 
~`/home/shared/8TB_HDD_01/sr320/github/steven-crabby-duck/F143_cgigas_sorted.bam`~

and continue downstream pointing to this bam.

**Comment by sr320** [comment]
sorry! wrong path...

`/home/shared/8TB_HDD_01/sr320/github/steven-crabby-duck/output/F143_cgigas_sorted.bam`

**Comment by sarahtanja** [comment]
That's ok I figure that out ;)
