### ISSUE TITLE
struggles trying to trim primers

### ISSUE THREAD

**Issue by hailaschultz** [course-fish546-2023/assistance-public#2]
I have been trying to start trimming the primers from my fastq files, but I am getting stuck at a few points. I tried to use grep to search the forward read primer sequence in my files, but nothing is coming up. Do you think I am searching this wrong, or could I have the wrong primer sequences? 

I am also having a hard time downloading cutadapt, which I was planning on using to actually trim the primers. I am trying to download it using the instructions here: https://cutadapt.readthedocs.io/en/stable/installation.html. I tried to install miniconda first, but I don't know where to go from here, as I don't understand how the whole conda system works. Do you know of an easy way to do this?

For reference, I am trying to adapt this pipeline to my needs: https://benjjneb.github.io/dada2/ITS_workflow.html#:~:text=After%20installing%20cutadapt%2C%20we%20need,path%20to%20the%20cutadapt%20command.&text=If%20the%20above%20command%20succesfully,to%20give%20the%20cutadapt%20command.

**Comment by sr320** [comment]
on raven I did this on terminal to install.. 

```
conda config --add channels bioconda
conda config --add channels conda-forge
conda create -n cutadaptenv cutadapt
```

Then activate the environment. This needs to be done every time you open a new shell before you can use Cutadapt:

```
conda activate cutadaptenv
```
